### PR TITLE
explict convert gbk chartset to utf-8,resolved chinese character disp…

### PR DESCRIPTION
**Pull request by laywin**
problem detail please see https://discuss.elastic.co/t/logstash-snmptrap-chinese-incorrect-codes/69509

### CODE REVIEW

**Comment by karmi** [comment]
Hi @laywin, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-input-snmptrap/pull/20.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by laywin** [comment]
@karmi ok!

**Comment by laywin** [comment]
@karmi  have aready added,please try again.

**Comment by andrewvc** [comment]
@laywin looks like it passed the CLA check! I'll review your PR this week.

**Comment by andrewvc** [comment]
@laywin , this patch would convert *all* UTF-8 to gbk. We definitely don't want that. @jordansissel what is your preferred approach here? Should we have a new `encoding` option that lets users deal with non-utf encodings?

**Comment by andrewvc** [comment]
This should probably use the same approach as the `plain-codec` uses here: https://github.com/logstash-plugins/logstash-codec-plain/blob/master/lib/logstash/codecs/plain.rb#L25

**Comment by laywin** [comment]
@andrewvc,yeah,but i tested codec,set charset to utf-8 or gbk,it doesn't work.

**Comment by andrewvc** [comment]
@laywin I think you misunderstand. I'm asking that you amend your patch to add a `charset` option directly to the plugin. A codec won't be used by the snmptrap plugin because snmp data is already structured. I was merely referencing the plain codec because its code could be copied directly into this plugin.

**Comment by andrewvc** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
